import { StyleSheet } from 'react-native';
import { AuthSession } from 'expo';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#81968F',
  },
  input: {
    width: 250,
    height: 50,
    padding: 10,
    borderWidth: 1,
    borderColor: 'black',
    marginBottom: 10,
    backgroundColor: 'white',
  },
  input2: {
    width: 133,
    height: 30,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
    borderWidth: 1,
    borderColor: 'black',
    marginBottom: 5,
    marginRight: 9,
    backgroundColor: 'white',
  },
  header3: {
    padding: 10,
    fontSize: 15,
    alignSelf: 'flex-start',
  },
  button: {
    backgroundColor: '#0275D8',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    width: 200,
  },
  buttonLargeMargin: {
    backgroundColor: '#0275D8',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 20,
    padding: 10,
    borderRadius: 10,
    width: 200,
  },
  buttonSmall: {
    backgroundColor: '#0275D8',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    width: 70,
  },
  buttonSmallDownPadding: {
    backgroundColor: '#0275D8',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 20,
    padding: 10,
    borderRadius: 10,
    width: 70,
  },
  buttonDeleteAccount: {
    backgroundColor: '#ff0000',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    width: 200,
  },
  text: {
    width: 250,
    padding: 10,
    marginBottom: 10,
    color: '#000000',
    fontSize: 20,
    alignSelf: 'flex-start',
    textAlignVertical: 'top'
  },
  textSmallPadding: {
    width: 250,
    padding: 5,
    color: '#000000',
    fontSize: 20,
    alignSelf: 'flex-start',
    textAlignVertical: 'top'
  },
  textCenter: {
    color: '#000000',
    fontSize: 20,
    alignSelf: 'center',
  },
  textWhite: {
    color: '#ffffff',
  },
  header1: {
    marginTop: 50,
    fontSize: 50,
    alignSelf: 'center',
  },
  header2: {
    fontSize: 20,
    alignSelf: 'flex-start',
  },
  sameRow: {
    width: 300,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sameRowLeft: {
    width: 300,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  sameRowCenter: {
    width: 300,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  signup: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    margin: 10,
    textDecoration: "underline",
  },
  logout: {
    backgroundColor: '#0275D8',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    margin: 10,
    marginBottom: 40,
    borderRadius: 10,
    width: 200,
  },
  view1 :{
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn1: {
    backgroundColor: '#0275D8',
    padding: 10,
    margin: 10,
  },

});